apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: tinyproxy-image-build
resources:
- buildconfig.yaml
- imagestream.yaml

secretGenerator:
  - name: github-webhook-secret
    options:
      disableNameSuffixHash: true
    literals:
      - WebHookSecretKey=tinyproxy
